server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SERVICE-A
          uri: lb://SERVICE-A/
          predicates:
            - Path=/servicea/**

        - id: SERVICE-B
          uri: lb://SERVICE-B/
          predicates:
            - Path=/**
  main:
    web-application-type: reactive

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/